os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: '9'
      # PYTHON2.7 REQUIRED FOR NODE-GYP & ELECTRON
      PYTHON2: "C:\\Python27"
      PYTHON2_VERSION: "2.7.9"
      PYTHON2_ARCH: "64"
    - nodejs_version: '8'
      PYTHON2: "C:\\Python27"
      PYTHON2_VERSION: "2.7.9"
      PYTHON2_ARCH: "64"
    - nodejs_version: '6'
      PYTHON2: "C:\\Python27"
      PYTHON2_VERSION: "2.7.9"
      PYTHON2_ARCH: "64"
    - nodejs_version: '4'
      PYTHON2: "C:\\Python27"
      PYTHON2_VERSION: "2.7.9"
      PYTHON2_ARCH: "64"

  PIP2: C:\\Python27\Scripts\pip

  npm_config_arch: x64

platform: x64

configuration: Release

skip_commits:
  files:
    - docs/*
    - Dockerfile
    - travis.yml
    - '**/*.html'
    - '*.md'

init:
  - cmd: node --version
  - cmd: npm --version

  - "ECHO Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture
  - cmd: npm config set msvs_version 2015 --global

  - cmd: ECHO %PYTHON2% %PYTHON2_VERSION% %PYTHON2_ARCH%
  - cmd: "%PYTHON2%\\python --version"
  - cmd: "%PYTHON2%\\python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - cmd: "%PYTHON2%\\python -m pip install --upgrade pip"

  - ps: Install-Product node $env:nodejs_version
  - cmd: node --version
  - cmd: npm --version
    # CRITICAL FOR NODE-GYP TO WORK
  - cmd: npm -g install npm@5.3 #TODO restore to npm@latest when npm stops breaking builds https://github.com/npm/npm/issues/18380
  - cmd: npm --version

  # SET THE RELEVANT PYTHON AND PIP LOCATIONS IN THE PATH
  - cmd: set PATH=%PYTHON2%;%PYTHON2%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

install:
  # Install gnats
  - appveyor DownloadFile https://github.com/nats-io/gnatsd/releases/download/v1.0.2/gnatsd-v1.0.2-windows-386.zip
  - 7z e gnatsd-v1.0.2-windows-386.zip gnatsd.exe -r -oc:\projects\hemera\build
  - cmd: set PATH=%PATH%;C:\projects\hemera\build

  - cmd: "%PIP2% freeze"

  # ADDITIONAL NPM PREP FOR ELECTRON APP BUILD
  - cmd: npm config list
  - cmd: npm config set python %PYTHON2%\python.exe --global

  - npm run setup
  - npm run test

build: off
