environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '7'

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - node --version
  - npm --version
  - npm run setup
  - npm run test

build: off